Repository meilisearch/meilisearch-java, pull requests merged in 2021-10, with the labels that each got.

#222 #197: Add support for filter arrays and nested filters
  src/main/java/com/meilisearch/sdk/Search.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/SearchRequestTest.java
Labels: breaking-change, hacktoberfest-accepted

#223 Implemented a better way to add documents in the Getting Started code example
  README.md
Labels: skip-changelog, hacktoberfest-accepted

#224 #78: addDocuments and updateDocuments should take pk as optional param
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/test/java/com/meilisearch/integration/DocumentsTest.java
Labels: hacktoberfest-accepted

#226 Update README.md with custom json,client and http requests
  README.md
Labels: skip-changelog
