Repository meilisearch/meilisearch-java, pull requests merged in 2022-12, with the labels that each got.

#502 Developer experience enhancements
  .editorconfig
  .gitignore
  build.gradle
Labels: enhancement

#510 Apply tasks changes
  src/main/java/com/meilisearch/sdk/Client.java
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/IndexesHandler.java
  src/main/java/com/meilisearch/sdk/SettingsHandler.java
  src/main/java/com/meilisearch/sdk/TasksHandler.java
  src/main/java/com/meilisearch/sdk/model/TaskInfo.java
  src/main/java/com/meilisearch/sdk/model/TasksQuery.java
  src/main/java/com/meilisearch/sdk/model/TasksResults.java
  src/test/java/com/meilisearch/integration/ClientTest.java
  src/test/java/com/meilisearch/integration/DocumentsTest.java
  src/test/java/com/meilisearch/integration/InstanceTest.java
  src/test/java/com/meilisearch/integration/SearchNestedTest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/integration/SettingsTest.java
  src/test/java/com/meilisearch/integration/TasksTest.java
  src/test/java/com/meilisearch/integration/TenantTokenTest.java
  src/test/java/com/meilisearch/integration/classes/AbstractIT.java
Labels: breaking-change

#508 Rename Result class to Results
  src/main/java/com/meilisearch/sdk/Client.java
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/IndexesHandler.java
  src/main/java/com/meilisearch/sdk/KeysHandler.java
  src/main/java/com/meilisearch/sdk/SettingsHandler.java
  src/main/java/com/meilisearch/sdk/TasksHandler.java
  src/main/java/com/meilisearch/sdk/model/Result.java
  src/main/java/com/meilisearch/sdk/model/Results.java
  src/main/java/com/meilisearch/sdk/model/TaskInfo.java
  src/main/java/com/meilisearch/sdk/model/TasksQuery.java
  src/main/java/com/meilisearch/sdk/model/TasksResults.java
  src/test/java/com/meilisearch/integration/ClientTest.java
  src/test/java/com/meilisearch/integration/DocumentsTest.java
  src/test/java/com/meilisearch/integration/InstanceTest.java
  src/test/java/com/meilisearch/integration/KeysTest.java
  src/test/java/com/meilisearch/integration/SearchNestedTest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/integration/SettingsTest.java
  src/test/java/com/meilisearch/integration/TasksTest.java
  src/test/java/com/meilisearch/integration/TenantTokenTest.java
  src/test/java/com/meilisearch/integration/classes/AbstractIT.java
Labels: breaking-change

#514 Modify setup-java in ci workflow for v3
  .github/workflows/pre-release-tests.yml
Labels: bug
