Repository meilisearch/meilisearch-java, pull requests merged in 2022-05, with the labels that each got.

#370 Fix test due to changes v0.27.0
  src/test/java/com/meilisearch/integration/SearchTest.java
Labels: skip-changelog

#375 Add new search parameters highlightPreTag, highlightPostTag and cropMarker
  src/main/java/com/meilisearch/sdk/Search.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/SearchRequestTest.java
Labels: enhancement

#374 Ensure nested field support
  src/test/java/com/meilisearch/integration/SearchNestedTest.java
  src/test/java/com/meilisearch/integration/classes/AbstractIT.java
Labels: maintenance

#377 Updating code-sample for v0.27.0
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#383 Update version for the next release (v0.7.2)
  .code-samples.meilisearch.yaml
  README.md
Labels: skip-changelog

#385 replaced traditional getter setter with lombok getter setter
  src/main/java/com/meilisearch/sdk/Config.java
  src/main/java/com/meilisearch/sdk/Details.java
  src/main/java/com/meilisearch/sdk/Dump.java
  src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
  src/main/java/com/meilisearch/sdk/Key.java
  src/main/java/com/meilisearch/sdk/Result.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/main/java/com/meilisearch/sdk/Settings.java
  src/main/java/com/meilisearch/sdk/Task.java
  src/main/java/com/meilisearch/sdk/TaskError.java
  src/main/java/com/meilisearch/sdk/TenantTokenOptions.java
  src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
  src/main/java/com/meilisearch/sdk/api/documents/SearchResponse.java
  src/main/java/com/meilisearch/sdk/api/documents/Task.java
  src/main/java/com/meilisearch/sdk/api/index/Index.java
  src/main/java/com/meilisearch/sdk/api/index/Settings.java
  src/main/java/com/meilisearch/sdk/api/instance/IndexStats.java
  src/main/java/com/meilisearch/sdk/api/instance/Stats.java
  src/main/java/com/meilisearch/sdk/http/request/BasicHttpRequest.java
  src/main/java/com/meilisearch/sdk/http/response/BasicHttpResponse.java
  src/main/java/com/meilisearch/sdk/model/SearchResult.java
Labels: enhancement
