Repository meilisearch/meilisearch-java, pull requests merged in 2023-10, with the labels that each got.

#661 Replace deprecated publish plugin
  .github/workflows/ossrh-publish.yml
  build.gradle
Labels: maintenance

#670 Add re-interrupt to waitForTask method
  src/main/java/com/meilisearch/sdk/TasksHandler.java
Labels: bug

#676 Change reference url in javadoc to see tag
  src/main/java/com/meilisearch/sdk/Client.java
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/IndexesHandler.java
  src/main/java/com/meilisearch/sdk/InstanceHandler.java
  src/main/java/com/meilisearch/sdk/KeysHandler.java
  src/main/java/com/meilisearch/sdk/Search.java
  src/main/java/com/meilisearch/sdk/SettingsHandler.java
  src/main/java/com/meilisearch/sdk/TasksHandler.java
  src/main/java/com/meilisearch/sdk/model/CancelTasksQuery.java
  src/main/java/com/meilisearch/sdk/model/DeleteTasksQuery.java
  src/main/java/com/meilisearch/sdk/model/DocumentQuery.java
  src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java
  src/main/java/com/meilisearch/sdk/model/IndexStats.java
  src/main/java/com/meilisearch/sdk/model/IndexesQuery.java
  src/main/java/com/meilisearch/sdk/model/Key.java
  src/main/java/com/meilisearch/sdk/model/KeyUpdate.java
  src/main/java/com/meilisearch/sdk/model/KeysQuery.java
  src/main/java/com/meilisearch/sdk/model/SearchResult.java
  src/main/java/com/meilisearch/sdk/model/SearchResultPaginated.java
  src/main/java/com/meilisearch/sdk/model/Searchable.java
  src/main/java/com/meilisearch/sdk/model/Settings.java
  src/main/java/com/meilisearch/sdk/model/Stats.java
  src/main/java/com/meilisearch/sdk/model/Task.java
  src/main/java/com/meilisearch/sdk/model/TaskInfo.java
  src/main/java/com/meilisearch/sdk/model/TaskStatus.java
  src/main/java/com/meilisearch/sdk/model/TasksQuery.java
  src/main/java/com/meilisearch/sdk/model/TasksResults.java
  src/main/java/com/meilisearch/sdk/model/TypoTolerance.java
Labels: documentation, enhancement
