Repository meilisearch/meilisearch-java, pull requests merged in 2023-09, with the labels that each got.

#649 Update code samples for april 2023
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#647 Move TenantTokenOptions to correct location, matching its package declaration
  src/main/java/com/meilisearch/sdk/TenantTokenOptions.java
Labels: enhancement, maintenance

#650 Fill missing code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#657 Remove useless code samples and add missing ones
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#656 Mark internal fields as transient
  src/main/java/com/meilisearch/sdk/Index.java
  src/test/java/com/meilisearch/integration/ClientTest.java
Labels: bug
