Repository meilisearch/meilisearch-java, pull requests merged in 2023-02, with the labels that each got.

#539 Correction of naming methods related to Ranking Rules
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/SettingsHandler.java
  src/test/java/com/meilisearch/integration/SettingsTest.java
Labels: breaking-change

#542 Update version for the next release (v0.10.0)
  .code-samples.meilisearch.yaml
  README.md
  build.gradle
  src/main/java/com/meilisearch/sdk/Version.java
Labels: skip-changelog

#543 Add a builder for SearchRequest class
  src/main/java/com/meilisearch/sdk/Search.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/test/java/com/meilisearch/integration/SearchNestedTest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/SearchRequestTest.java
Labels: enhancement, breaking-change

#551 Fix: #550 added constructor to initialize HttpClient using Gson by default
  README.md
  src/main/java/com/meilisearch/sdk/Config.java
Labels: bug

#544 Add tasks filters for v0.30
  src/main/java/com/meilisearch/sdk/TasksHandler.java
  src/main/java/com/meilisearch/sdk/http/URLBuilder.java
  src/main/java/com/meilisearch/sdk/model/TasksQuery.java
  src/test/java/com/meilisearch/integration/TasksTest.java
  src/test/java/com/meilisearch/sdk/TaskHandlerUtilsTest.java
  src/test/java/com/meilisearch/sdk/http/URLBuilderTest.java
Labels: breaking-change

#554 Add swap indexes api for v0.30.0
  src/main/java/com/meilisearch/sdk/Client.java
  src/main/java/com/meilisearch/sdk/model/SwapIndexesParams.java
  src/main/java/com/meilisearch/sdk/model/TaskDetails.java
  src/test/java/com/meilisearch/integration/ClientTest.java
Labels: enhancement

#555 Adding a version to be changed in the contributing
  CONTRIBUTING.md
Labels: skip-changelog

#558 Implement `getRawIndexes` with query parameters
  src/main/java/com/meilisearch/sdk/Client.java
  src/main/java/com/meilisearch/sdk/IndexesHandler.java
  src/test/java/com/meilisearch/integration/ClientTest.java
Labels: enhancement

#546 Add pagination feature for v0.30.0
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/Search.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/main/java/com/meilisearch/sdk/model/SearchResult.java
  src/main/java/com/meilisearch/sdk/model/SearchResultPaginated.java
  src/main/java/com/meilisearch/sdk/model/Searchable.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/SearchRequestTest.java
Labels: breaking-change

#561 Fix matching strategy enum usage and add test
  src/main/java/com/meilisearch/sdk/Search.java
  src/test/java/com/meilisearch/integration/SearchTest.java
Labels: bug
