Repository meilisearch/meilisearch-java, pull requests merged in 2024-05, with the labels that each got.

#724 Add support to get documents by filter
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java
  src/test/java/com/meilisearch/integration/DocumentsTest.java
Labels: enhancement

#734 fix WaitForTask timeout in case of a task cancellation
  src/main/java/com/meilisearch/sdk/TasksHandler.java
Labels: bug

#733 Add ranking score search parameter
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/utils/Movie.java
Labels: enhancement

#735 Add facet search support
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/FacetSearch.java
  src/main/java/com/meilisearch/sdk/FacetSearchRequest.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/main/java/com/meilisearch/sdk/model/FacetSearchResult.java
  src/main/java/com/meilisearch/sdk/model/FacetSearchable.java
Labels: enhancement

#743 Add showRankingScoreDetails in search
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/IndexSearchRequest.java
  src/main/java/com/meilisearch/sdk/SearchRequest.java
  src/test/java/com/meilisearch/integration/SearchTest.java
  src/test/java/com/meilisearch/sdk/utils/Movie.java
Labels: enhancement

#741 Add ability to delete document by filter
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/Documents.java
  src/main/java/com/meilisearch/sdk/Index.java
  src/test/java/com/meilisearch/integration/DocumentsTest.java
Labels: enhancement

#738 Adjust the targetClass parameter variable of the decode method in JsonHandler from class<?> to class<T>
  src/main/java/com/meilisearch/sdk/json/GsonJsonHandler.java
  src/main/java/com/meilisearch/sdk/json/JacksonJsonHandler.java
  src/main/java/com/meilisearch/sdk/json/JsonHandler.java
Labels: maintenance

#739 Add sort facets value feature
  .code-samples.meilisearch.yaml
  src/main/java/com/meilisearch/sdk/model/FacetSortValue.java
  src/main/java/com/meilisearch/sdk/model/Faceting.java
  src/test/java/com/meilisearch/integration/SettingsTest.java
Labels: enhancement
